### ISSUE TITLE
The Radar Booster after being turned off can be used to teleport fake players while solo.

### ISSUE THREAD

**Issue by wolf653** [MrHydralisk/Lethal-Company-Enhanced-Radar-Booster#11]
See attached link, in short pretty harmless but in vanilla this is fixed because while turning off the radar booster sets the monitor to `Player #1` it still sets it to an actual player while teleporting. https://imgur.com/a/913r9EJ

**Comment by MrHydralisk** [comment]
What if I tell you, that this is a vanilla feature and not related to this mod?

Not the first time someone mentioning this to me. People just seems to be using Radar Boosters more often, when have ERB mod installed, so they actually enounter this vanilla code bug.

**Comment by wolf653** [comment]
> What if I tell you, that this is a vanilla feature and not related to this mod?
> 
> Not the first time someone mentioning this to me. People just seems to be using Radar Boosters more often, when have ERB mod installed, so they actually encounter this vanilla code bug.

Here is the thing, I actually tested this in vanilla as well, and when you try teleporting the fake player it automatically switches to a real one. I even acknowledge this _but in vanilla this is fixed because while turning off the radar booster sets the monitor to Player #1 it still sets it to an actual player while teleporting._

**Comment by MrHydralisk** [comment]
Well, I tested it in vanilla when was responding first time and it was having same issue.

**Comment by MrHydralisk** [comment]
Tested again. No mods at all. Still same issue of creating new non-existent player:
![image](https://github.com/MrHydralisk/Lethal-Company-Enhanced-Radar-Booster/assets/113328125/d9fa6b8c-91eb-4cda-a007-274c79d22f0b)
![image](https://github.com/MrHydralisk/Lethal-Company-Enhanced-Radar-Booster/assets/113328125/04675557-b6c0-4809-be22-ca692be62312)
