### ISSUE TITLE
[Feedback] Should have a option, Teleport player to Radar won't drop specified items

### ISSUE THREAD

**Issue by CoolLKKPS** [MrHydralisk/Lethal-Company-Enhanced-Radar-Booster#12]
this is for LC_CustomDifficulty, that mod will be really hard if don't have this option

**Comment by MrHydralisk** [comment]
Some mods like Better Teleporter already have this feature and, since ERB mod just changing the end point of inverse teleportation, so that feature from it works for teleporting to Radar Booster too.

**Comment by MrHydralisk** [comment]
But aren't it then suppose to be asked from backroom mod dev then? Cause I don't change or add logic to teleportation itself. Or do I miss smf? Does it needed only for backrooms or other mods?
