### ISSUE TITLE
Reduce flash?

### ISSUE THREAD

**Issue by JZomDev** [MrHydralisk/Lethal-Company-Enhanced-Radar-Booster#16]
If not added to this plugin, is it possible to reduce the flash on the flash of the radar booster? It's sorta impossible to navigate back when the terminal operator has to spam flash sam over and over to prevent a giant from eating them

**Comment by MrHydralisk** [comment]
Tbh, I not really worked with flash or how it works itself, but just called vanilla method. I not sure but it might be coded to light source of RB. And technically I would rather not change the flash intencity itself, cause it def was intended by LC dev as counter to it abuse in combat.

**Comment by JZomDev** [comment]
While I agree that the intensity is a choice by the developer you can extend that almost everything. The sounds in the game, the textures and the way the game works. Mods are used to modify or replace mechanics in the game. 

It doesn't need to be part of this mod, I was briefly trying to see how I could accomplish it but I realize i don't have a baseline of understanding of how to do it nor an existing mod that does anything similar to my request. 

If not part of this mod, would you be interested in a flash tweaker?

**Comment by MrHydralisk** [comment]
Tbh, I kinda fully packed with current projects that I have and irl, so I doubt it will be any time soon on my list, if it happens at all.

**Comment by JZomDev** [comment]
That’s a perfectly fine response and reason. I appreciate your time. :)On Feb 17, 2024, at 5:16 PM, MrHydralisk ***@***.***> wrote:﻿
Tbh, I kinda fully packed with current projects that I have and irl, so I doubt it will be any time soon on my list, if it happens at all.
