### ISSUE TITLE
the radar keeps appearing after leaving the moon

### ISSUE THREAD

**Issue by slovinsqui** [MrHydralisk/Lethal-Company-Enhanced-Radar-Booster#6]
for some reason, when I inversed teleported the radar booster, after going to other moon, the radar booster spawned inside the building of  that moon, this kept happening after many moon travels 

its really freaky because it kinda matches the ship landing movement when starting the day, I could see the map as soon as I landed because of the radar already being inside

**Comment by MrHydralisk** [comment]
Ye, I noticed that myself too, seems to be radar booster being parented to ship even after teleportation and not being destroyed with other loot outside the ship, if left without retrieval.

**Comment by MrHydralisk** [comment]
Fixed with #18
